# Generated by Django 4.2.16 on 2025-08-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('campaign_manager', 'Campaign Manager'), ('superadmin', 'Super Admin')], default='donor', max_length=20, verbose_name='role'),
        ),
    ]
