# Generated by Django 4.2.16 on 2025-08-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0003_campaign_customuser_gender_payment_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
